vich_uploader:
    db_driver: orm
    metadata:
       type: attribute

    mappings:
       bird_Specy:
           uri_prefix: /images/bird_Specy
           upload_destination: '%kernel.project_dir%/public/images/bird_Specy'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true

       userImage:
           uri_prefix: /images/userImage
           upload_destination: '%kernel.project_dir%/public/images/userImage'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true

       images:
           uri_prefix: /images/all
           upload_destination: '%kernel.project_dir%/public/images/all'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
