<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241023081401 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE agents_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bird_family_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bird_life_tax_treat_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bird_species_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bird_species_count_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE campaign_status_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE city_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE collected_data_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE count_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE counting_campaign_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE country_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE coverage_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE disturbed_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE environmental_conditions_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ice_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE image_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE iucn_red_list_category_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE logo_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE method_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE nature_reserve_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE quality_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE region_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reset_password_request_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE site_agents_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE site_collection_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tidal_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE user_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE water_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE weather_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE agents_group (id INT NOT NULL, leader_id INT NOT NULL, country_id INT NOT NULL, created_by_id INT NOT NULL, group_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B102AC9773154ED4 ON agents_group (leader_id)');
        $this->addSql('CREATE INDEX IDX_B102AC97F92F3E70 ON agents_group (country_id)');
        $this->addSql('CREATE INDEX IDX_B102AC97B03A8386 ON agents_group (created_by_id)');
        $this->addSql('COMMENT ON COLUMN agents_group.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN agents_group.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE agents_group_user (agents_group_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY(agents_group_id, user_id))');
        $this->addSql('CREATE INDEX IDX_4A77B07872A1F93D ON agents_group_user (agents_group_id)');
        $this->addSql('CREATE INDEX IDX_4A77B078A76ED395 ON agents_group_user (user_id)');
        $this->addSql('CREATE TABLE bird_family (id INT NOT NULL, family_name VARCHAR(255) NOT NULL, sub_family VARCHAR(255) DEFAULT NULL, tribe VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ordre VARCHAR(255) NOT NULL, family VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN bird_family.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN bird_family.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE bird_life_tax_treat (id INT NOT NULL, label VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN bird_life_tax_treat.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN bird_life_tax_treat.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE bird_species (id INT NOT NULL, bird_family_id INT DEFAULT NULL, coverage_id INT DEFAULT NULL, bird_life_tax_treat_id INT DEFAULT NULL, iucn_red_list_category_id INT DEFAULT NULL, image_id INT DEFAULT NULL, scientific_name VARCHAR(255) NOT NULL, french_name VARCHAR(255) DEFAULT NULL, wispeciescode VARCHAR(255) DEFAULT NULL, authority VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, common_name VARCHAR(255) DEFAULT NULL, common_name_alt VARCHAR(100) DEFAULT NULL, synonyms VARCHAR(255) DEFAULT NULL, taxonomic_sources VARCHAR(500) DEFAULT NULL, sis_rec_id INT DEFAULT NULL, spc_rec_id INT DEFAULT NULL, subspp_id VARCHAR(255) DEFAULT NULL, english_name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D373D04E705A8725 ON bird_species (bird_family_id)');
        $this->addSql('CREATE INDEX IDX_D373D04E9F5AA71B ON bird_species (coverage_id)');
        $this->addSql('CREATE INDEX IDX_D373D04E902F3AE5 ON bird_species (bird_life_tax_treat_id)');
        $this->addSql('CREATE INDEX IDX_D373D04E6E09E6BF ON bird_species (iucn_red_list_category_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D373D04E3DA5256D ON bird_species (image_id)');
        $this->addSql('COMMENT ON COLUMN bird_species.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN bird_species.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE bird_species_count (id INT NOT NULL, collected_data_id INT NOT NULL, bird_species_id INT DEFAULT NULL, count INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_450338A0EDED93F9 ON bird_species_count (collected_data_id)');
        $this->addSql('CREATE INDEX IDX_450338A0547180B0 ON bird_species_count (bird_species_id)');
        $this->addSql('CREATE TABLE campaign_status (id INT NOT NULL, label VARCHAR(25) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN campaign_status.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN campaign_status.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE city (id INT NOT NULL, region_id INT NOT NULL, name VARCHAR(255) NOT NULL, latitude VARCHAR(255) NOT NULL, longitude VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2D5B023498260155 ON city (region_id)');
        $this->addSql('COMMENT ON COLUMN city.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN city.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE collected_data (id INT NOT NULL, counting_campaign_id INT NOT NULL, site_collection_id INT NOT NULL, created_by_id INT NOT NULL, count_type_id INT NOT NULL, quality_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_79374E7C60B458C7 ON collected_data (counting_campaign_id)');
        $this->addSql('CREATE INDEX IDX_79374E7C3EA3E56 ON collected_data (site_collection_id)');
        $this->addSql('CREATE INDEX IDX_79374E7CB03A8386 ON collected_data (created_by_id)');
        $this->addSql('CREATE INDEX IDX_79374E7CDFB9E947 ON collected_data (count_type_id)');
        $this->addSql('CREATE INDEX IDX_79374E7CBCFC6D57 ON collected_data (quality_id)');
        $this->addSql('COMMENT ON COLUMN collected_data.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN collected_data.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE collected_data_bird_species (collected_data_id INT NOT NULL, bird_species_id INT NOT NULL, PRIMARY KEY(collected_data_id, bird_species_id))');
        $this->addSql('CREATE INDEX IDX_7B39E3BBEDED93F9 ON collected_data_bird_species (collected_data_id)');
        $this->addSql('CREATE INDEX IDX_7B39E3BB547180B0 ON collected_data_bird_species (bird_species_id)');
        $this->addSql('CREATE TABLE collected_data_method (collected_data_id INT NOT NULL, method_id INT NOT NULL, PRIMARY KEY(collected_data_id, method_id))');
        $this->addSql('CREATE INDEX IDX_BCC68720EDED93F9 ON collected_data_method (collected_data_id)');
        $this->addSql('CREATE INDEX IDX_BCC6872019883967 ON collected_data_method (method_id)');
        $this->addSql('CREATE TABLE count_type (id INT NOT NULL, label VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN count_type.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN count_type.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE counting_campaign (id INT NOT NULL, created_by_id INT NOT NULL, campaign_status_id INT DEFAULT NULL, campaign_name VARCHAR(255) NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_55508ABB03A8386 ON counting_campaign (created_by_id)');
        $this->addSql('CREATE INDEX IDX_55508ABAB7F1CC6 ON counting_campaign (campaign_status_id)');
        $this->addSql('COMMENT ON COLUMN counting_campaign.start_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN counting_campaign.end_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN counting_campaign.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN counting_campaign.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE country (id INT NOT NULL, name VARCHAR(255) NOT NULL, iso2 VARCHAR(2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN country.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN country.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE coverage (id INT NOT NULL, label VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN coverage.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN coverage.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE disturbed (id INT NOT NULL, label VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN disturbed.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN disturbed.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE environmental_conditions (id INT NOT NULL, disturbed_id INT NOT NULL, ice_id INT NOT NULL, tidal_id INT NOT NULL, water_id INT NOT NULL, weather_id INT NOT NULL, collected_data_id INT DEFAULT NULL, site_collection_id INT NOT NULL, counting_campaign_id INT NOT NULL, user_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_96C106D26DC4E10B ON environmental_conditions (disturbed_id)');
        $this->addSql('CREATE INDEX IDX_96C106D2D553E9BF ON environmental_conditions (ice_id)');
        $this->addSql('CREATE INDEX IDX_96C106D28CD10E1D ON environmental_conditions (tidal_id)');
        $this->addSql('CREATE INDEX IDX_96C106D27721C36E ON environmental_conditions (water_id)');
        $this->addSql('CREATE INDEX IDX_96C106D28CE675E ON environmental_conditions (weather_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_96C106D2EDED93F9 ON environmental_conditions (collected_data_id)');
        $this->addSql('CREATE INDEX IDX_96C106D23EA3E56 ON environmental_conditions (site_collection_id)');
        $this->addSql('CREATE INDEX IDX_96C106D260B458C7 ON environmental_conditions (counting_campaign_id)');
        $this->addSql('CREATE INDEX IDX_96C106D2A76ED395 ON environmental_conditions (user_id)');
        $this->addSql('COMMENT ON COLUMN environmental_conditions.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN environmental_conditions.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE ice (id INT NOT NULL, label VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN ice.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN ice.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE image (id INT NOT NULL, image_filename VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN image.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN image.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE iucn_red_list_category (id INT NOT NULL, label VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN iucn_red_list_category.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN iucn_red_list_category.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE logo (id INT NOT NULL, image_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E48E9A133DA5256D ON logo (image_id)');
        $this->addSql('COMMENT ON COLUMN logo.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN logo.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE method (id INT NOT NULL, label VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN method.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN method.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE nature_reserve (id INT NOT NULL, created_by_id INT NOT NULL, reserve_leader_id INT NOT NULL, reserve_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_763A1F7B03A8386 ON nature_reserve (created_by_id)');
        $this->addSql('CREATE INDEX IDX_763A1F7C87FFE17 ON nature_reserve (reserve_leader_id)');
        $this->addSql('COMMENT ON COLUMN nature_reserve.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN nature_reserve.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE quality (id INT NOT NULL, label VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN quality.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN quality.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE region (id INT NOT NULL, country_id INT NOT NULL, name VARCHAR(255) NOT NULL, region_code VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F62F176F92F3E70 ON region (country_id)');
        $this->addSql('COMMENT ON COLUMN region.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN region.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE reset_password_request (id INT NOT NULL, user_id INT NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('COMMENT ON COLUMN reset_password_request.requested_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN reset_password_request.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE site_agents_group (id INT NOT NULL, counting_campaign_id INT NOT NULL, site_collection_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7A88312460B458C7 ON site_agents_group (counting_campaign_id)');
        $this->addSql('CREATE INDEX IDX_7A8831243EA3E56 ON site_agents_group (site_collection_id)');
        $this->addSql('COMMENT ON COLUMN site_agents_group.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN site_agents_group.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE site_agents_group_agents_group (site_agents_group_id INT NOT NULL, agents_group_id INT NOT NULL, PRIMARY KEY(site_agents_group_id, agents_group_id))');
        $this->addSql('CREATE INDEX IDX_3B5B54BD7C3B27D6 ON site_agents_group_agents_group (site_agents_group_id)');
        $this->addSql('CREATE INDEX IDX_3B5B54BD72A1F93D ON site_agents_group_agents_group (agents_group_id)');
        $this->addSql('CREATE TABLE site_collection (id INT NOT NULL, city_id INT NOT NULL, parent_site_id INT DEFAULT NULL, nature_reserve_id INT DEFAULT NULL, site_name VARCHAR(255) NOT NULL, site_code VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, national_site_code VARCHAR(255) DEFAULT NULL, international_site_code VARCHAR(255) DEFAULT NULL, lat_depart VARCHAR(255) NOT NULL, long_depart VARCHAR(255) NOT NULL, lat_fin VARCHAR(255) NOT NULL, long_fin VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DC44EAF78BAC62AF ON site_collection (city_id)');
        $this->addSql('CREATE INDEX IDX_DC44EAF784F56200 ON site_collection (parent_site_id)');
        $this->addSql('CREATE INDEX IDX_DC44EAF7B56D1D28 ON site_collection (nature_reserve_id)');
        $this->addSql('COMMENT ON COLUMN site_collection.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN site_collection.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE tidal (id INT NOT NULL, label VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN tidal.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN tidal.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE "user" (id INT NOT NULL, image_id INT DEFAULT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D6493DA5256D ON "user" (image_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "user".updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE water (id INT NOT NULL, label VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN water.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN water.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE weather (id INT NOT NULL, label VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN weather.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN weather.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE messenger_messages (id BIGSERIAL NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE OR REPLACE FUNCTION notify_messenger_messages() RETURNS TRIGGER AS $$
            BEGIN
                PERFORM pg_notify(\'messenger_messages\', NEW.queue_name::text);
                RETURN NEW;
            END;
        $$ LANGUAGE plpgsql;');
        $this->addSql('DROP TRIGGER IF EXISTS notify_trigger ON messenger_messages;');
        $this->addSql('CREATE TRIGGER notify_trigger AFTER INSERT OR UPDATE ON messenger_messages FOR EACH ROW EXECUTE PROCEDURE notify_messenger_messages();');
        $this->addSql('ALTER TABLE agents_group ADD CONSTRAINT FK_B102AC9773154ED4 FOREIGN KEY (leader_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agents_group ADD CONSTRAINT FK_B102AC97F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agents_group ADD CONSTRAINT FK_B102AC97B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agents_group_user ADD CONSTRAINT FK_4A77B07872A1F93D FOREIGN KEY (agents_group_id) REFERENCES agents_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agents_group_user ADD CONSTRAINT FK_4A77B078A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bird_species ADD CONSTRAINT FK_D373D04E705A8725 FOREIGN KEY (bird_family_id) REFERENCES bird_family (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bird_species ADD CONSTRAINT FK_D373D04E9F5AA71B FOREIGN KEY (coverage_id) REFERENCES coverage (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bird_species ADD CONSTRAINT FK_D373D04E902F3AE5 FOREIGN KEY (bird_life_tax_treat_id) REFERENCES bird_life_tax_treat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bird_species ADD CONSTRAINT FK_D373D04E6E09E6BF FOREIGN KEY (iucn_red_list_category_id) REFERENCES iucn_red_list_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bird_species ADD CONSTRAINT FK_D373D04E3DA5256D FOREIGN KEY (image_id) REFERENCES image (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bird_species_count ADD CONSTRAINT FK_450338A0EDED93F9 FOREIGN KEY (collected_data_id) REFERENCES collected_data (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bird_species_count ADD CONSTRAINT FK_450338A0547180B0 FOREIGN KEY (bird_species_id) REFERENCES bird_species (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B023498260155 FOREIGN KEY (region_id) REFERENCES region (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE collected_data ADD CONSTRAINT FK_79374E7C60B458C7 FOREIGN KEY (counting_campaign_id) REFERENCES counting_campaign (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE collected_data ADD CONSTRAINT FK_79374E7C3EA3E56 FOREIGN KEY (site_collection_id) REFERENCES site_collection (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE collected_data ADD CONSTRAINT FK_79374E7CB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE collected_data ADD CONSTRAINT FK_79374E7CDFB9E947 FOREIGN KEY (count_type_id) REFERENCES count_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE collected_data ADD CONSTRAINT FK_79374E7CBCFC6D57 FOREIGN KEY (quality_id) REFERENCES quality (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE collected_data_bird_species ADD CONSTRAINT FK_7B39E3BBEDED93F9 FOREIGN KEY (collected_data_id) REFERENCES collected_data (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE collected_data_bird_species ADD CONSTRAINT FK_7B39E3BB547180B0 FOREIGN KEY (bird_species_id) REFERENCES bird_species (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE collected_data_method ADD CONSTRAINT FK_BCC68720EDED93F9 FOREIGN KEY (collected_data_id) REFERENCES collected_data (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE collected_data_method ADD CONSTRAINT FK_BCC6872019883967 FOREIGN KEY (method_id) REFERENCES method (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE counting_campaign ADD CONSTRAINT FK_55508ABB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE counting_campaign ADD CONSTRAINT FK_55508ABAB7F1CC6 FOREIGN KEY (campaign_status_id) REFERENCES campaign_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE environmental_conditions ADD CONSTRAINT FK_96C106D26DC4E10B FOREIGN KEY (disturbed_id) REFERENCES disturbed (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE environmental_conditions ADD CONSTRAINT FK_96C106D2D553E9BF FOREIGN KEY (ice_id) REFERENCES ice (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE environmental_conditions ADD CONSTRAINT FK_96C106D28CD10E1D FOREIGN KEY (tidal_id) REFERENCES tidal (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE environmental_conditions ADD CONSTRAINT FK_96C106D27721C36E FOREIGN KEY (water_id) REFERENCES water (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE environmental_conditions ADD CONSTRAINT FK_96C106D28CE675E FOREIGN KEY (weather_id) REFERENCES weather (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE environmental_conditions ADD CONSTRAINT FK_96C106D2EDED93F9 FOREIGN KEY (collected_data_id) REFERENCES collected_data (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE environmental_conditions ADD CONSTRAINT FK_96C106D23EA3E56 FOREIGN KEY (site_collection_id) REFERENCES site_collection (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE environmental_conditions ADD CONSTRAINT FK_96C106D260B458C7 FOREIGN KEY (counting_campaign_id) REFERENCES counting_campaign (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE environmental_conditions ADD CONSTRAINT FK_96C106D2A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE logo ADD CONSTRAINT FK_E48E9A133DA5256D FOREIGN KEY (image_id) REFERENCES image (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nature_reserve ADD CONSTRAINT FK_763A1F7B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nature_reserve ADD CONSTRAINT FK_763A1F7C87FFE17 FOREIGN KEY (reserve_leader_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE region ADD CONSTRAINT FK_F62F176F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE site_agents_group ADD CONSTRAINT FK_7A88312460B458C7 FOREIGN KEY (counting_campaign_id) REFERENCES counting_campaign (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE site_agents_group ADD CONSTRAINT FK_7A8831243EA3E56 FOREIGN KEY (site_collection_id) REFERENCES site_collection (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE site_agents_group_agents_group ADD CONSTRAINT FK_3B5B54BD7C3B27D6 FOREIGN KEY (site_agents_group_id) REFERENCES site_agents_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE site_agents_group_agents_group ADD CONSTRAINT FK_3B5B54BD72A1F93D FOREIGN KEY (agents_group_id) REFERENCES agents_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE site_collection ADD CONSTRAINT FK_DC44EAF78BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE site_collection ADD CONSTRAINT FK_DC44EAF784F56200 FOREIGN KEY (parent_site_id) REFERENCES site_collection (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE site_collection ADD CONSTRAINT FK_DC44EAF7B56D1D28 FOREIGN KEY (nature_reserve_id) REFERENCES nature_reserve (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6493DA5256D FOREIGN KEY (image_id) REFERENCES image (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP SEQUENCE agents_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bird_family_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bird_life_tax_treat_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bird_species_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bird_species_count_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE campaign_status_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE city_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE collected_data_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE count_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE counting_campaign_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE country_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE coverage_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE disturbed_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE environmental_conditions_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ice_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE image_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE iucn_red_list_category_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE logo_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE method_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE nature_reserve_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE quality_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE region_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reset_password_request_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE site_agents_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE site_collection_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tidal_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE user_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE water_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE weather_id_seq CASCADE');
        $this->addSql('ALTER TABLE agents_group DROP CONSTRAINT FK_B102AC9773154ED4');
        $this->addSql('ALTER TABLE agents_group DROP CONSTRAINT FK_B102AC97F92F3E70');
        $this->addSql('ALTER TABLE agents_group DROP CONSTRAINT FK_B102AC97B03A8386');
        $this->addSql('ALTER TABLE agents_group_user DROP CONSTRAINT FK_4A77B07872A1F93D');
        $this->addSql('ALTER TABLE agents_group_user DROP CONSTRAINT FK_4A77B078A76ED395');
        $this->addSql('ALTER TABLE bird_species DROP CONSTRAINT FK_D373D04E705A8725');
        $this->addSql('ALTER TABLE bird_species DROP CONSTRAINT FK_D373D04E9F5AA71B');
        $this->addSql('ALTER TABLE bird_species DROP CONSTRAINT FK_D373D04E902F3AE5');
        $this->addSql('ALTER TABLE bird_species DROP CONSTRAINT FK_D373D04E6E09E6BF');
        $this->addSql('ALTER TABLE bird_species DROP CONSTRAINT FK_D373D04E3DA5256D');
        $this->addSql('ALTER TABLE bird_species_count DROP CONSTRAINT FK_450338A0EDED93F9');
        $this->addSql('ALTER TABLE bird_species_count DROP CONSTRAINT FK_450338A0547180B0');
        $this->addSql('ALTER TABLE city DROP CONSTRAINT FK_2D5B023498260155');
        $this->addSql('ALTER TABLE collected_data DROP CONSTRAINT FK_79374E7C60B458C7');
        $this->addSql('ALTER TABLE collected_data DROP CONSTRAINT FK_79374E7C3EA3E56');
        $this->addSql('ALTER TABLE collected_data DROP CONSTRAINT FK_79374E7CB03A8386');
        $this->addSql('ALTER TABLE collected_data DROP CONSTRAINT FK_79374E7CDFB9E947');
        $this->addSql('ALTER TABLE collected_data DROP CONSTRAINT FK_79374E7CBCFC6D57');
        $this->addSql('ALTER TABLE collected_data_bird_species DROP CONSTRAINT FK_7B39E3BBEDED93F9');
        $this->addSql('ALTER TABLE collected_data_bird_species DROP CONSTRAINT FK_7B39E3BB547180B0');
        $this->addSql('ALTER TABLE collected_data_method DROP CONSTRAINT FK_BCC68720EDED93F9');
        $this->addSql('ALTER TABLE collected_data_method DROP CONSTRAINT FK_BCC6872019883967');
        $this->addSql('ALTER TABLE counting_campaign DROP CONSTRAINT FK_55508ABB03A8386');
        $this->addSql('ALTER TABLE counting_campaign DROP CONSTRAINT FK_55508ABAB7F1CC6');
        $this->addSql('ALTER TABLE environmental_conditions DROP CONSTRAINT FK_96C106D26DC4E10B');
        $this->addSql('ALTER TABLE environmental_conditions DROP CONSTRAINT FK_96C106D2D553E9BF');
        $this->addSql('ALTER TABLE environmental_conditions DROP CONSTRAINT FK_96C106D28CD10E1D');
        $this->addSql('ALTER TABLE environmental_conditions DROP CONSTRAINT FK_96C106D27721C36E');
        $this->addSql('ALTER TABLE environmental_conditions DROP CONSTRAINT FK_96C106D28CE675E');
        $this->addSql('ALTER TABLE environmental_conditions DROP CONSTRAINT FK_96C106D2EDED93F9');
        $this->addSql('ALTER TABLE environmental_conditions DROP CONSTRAINT FK_96C106D23EA3E56');
        $this->addSql('ALTER TABLE environmental_conditions DROP CONSTRAINT FK_96C106D260B458C7');
        $this->addSql('ALTER TABLE environmental_conditions DROP CONSTRAINT FK_96C106D2A76ED395');
        $this->addSql('ALTER TABLE logo DROP CONSTRAINT FK_E48E9A133DA5256D');
        $this->addSql('ALTER TABLE nature_reserve DROP CONSTRAINT FK_763A1F7B03A8386');
        $this->addSql('ALTER TABLE nature_reserve DROP CONSTRAINT FK_763A1F7C87FFE17');
        $this->addSql('ALTER TABLE region DROP CONSTRAINT FK_F62F176F92F3E70');
        $this->addSql('ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE site_agents_group DROP CONSTRAINT FK_7A88312460B458C7');
        $this->addSql('ALTER TABLE site_agents_group DROP CONSTRAINT FK_7A8831243EA3E56');
        $this->addSql('ALTER TABLE site_agents_group_agents_group DROP CONSTRAINT FK_3B5B54BD7C3B27D6');
        $this->addSql('ALTER TABLE site_agents_group_agents_group DROP CONSTRAINT FK_3B5B54BD72A1F93D');
        $this->addSql('ALTER TABLE site_collection DROP CONSTRAINT FK_DC44EAF78BAC62AF');
        $this->addSql('ALTER TABLE site_collection DROP CONSTRAINT FK_DC44EAF784F56200');
        $this->addSql('ALTER TABLE site_collection DROP CONSTRAINT FK_DC44EAF7B56D1D28');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D6493DA5256D');
        $this->addSql('DROP TABLE agents_group');
        $this->addSql('DROP TABLE agents_group_user');
        $this->addSql('DROP TABLE bird_family');
        $this->addSql('DROP TABLE bird_life_tax_treat');
        $this->addSql('DROP TABLE bird_species');
        $this->addSql('DROP TABLE bird_species_count');
        $this->addSql('DROP TABLE campaign_status');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE collected_data');
        $this->addSql('DROP TABLE collected_data_bird_species');
        $this->addSql('DROP TABLE collected_data_method');
        $this->addSql('DROP TABLE count_type');
        $this->addSql('DROP TABLE counting_campaign');
        $this->addSql('DROP TABLE country');
        $this->addSql('DROP TABLE coverage');
        $this->addSql('DROP TABLE disturbed');
        $this->addSql('DROP TABLE environmental_conditions');
        $this->addSql('DROP TABLE ice');
        $this->addSql('DROP TABLE image');
        $this->addSql('DROP TABLE iucn_red_list_category');
        $this->addSql('DROP TABLE logo');
        $this->addSql('DROP TABLE method');
        $this->addSql('DROP TABLE nature_reserve');
        $this->addSql('DROP TABLE quality');
        $this->addSql('DROP TABLE region');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE site_agents_group');
        $this->addSql('DROP TABLE site_agents_group_agents_group');
        $this->addSql('DROP TABLE site_collection');
        $this->addSql('DROP TABLE tidal');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE water');
        $this->addSql('DROP TABLE weather');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
